version: '3'

services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        restart: always
        depends_on:
            - mysqldb
        volumes:
            - ./code:/code
        networks:
            - code-network
    composer:
        image: composer
        depends_on:
            - mysqldb
        volumes:
            - "./code:/code"
        command: install
        networks:
            - code-network

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysqlhost
        restart: always
        depends_on:
            - mysqldb
        networks:
            - code-network
    mysqldb:
        image: mysql
        container_name: mysqlhost
        restart: always
        environment:
            - MYSQL_DATABASE=phpdb
            - MYSQL_ROOT_PASSWORD=rootdb
            - MYSQL_USER=phpuser
            - MYSQL_PASSWORD=phpuser
        ports:
            - 8989:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge


